language: c
sudo: true

env:
  - CTEST_OUTPUT_ON_FAILURE=TRUE

install:
  # Install the Criterion unit testing framework
  - cd ${TRAVIS_BUILD_DIR}
  - cd dependencies/criterion/
  - cmake .
  - make
  - sudo make install
  - sudo ldconfig

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
