language: c
sudo: true

env:
  - CTEST_OUTPUT_ON_FAILURE=TRUE

install:
  # Install the Criterion unit testing framework
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir dependencies
  - cd dependencies
  - wget https://github.com/Snaipe/Criterion/releases/download/v2.2.2/criterion-v2.2.2-linux-x86_64.tar.bz2 -O criterion.tar.bz2
  - tar xvjf criterion.tar.bz2
  - mv criterion-v2.2.2/* .
  - sudo mv lib/libcriterion.so /usr/local/lib/libcriterion.so
  - sudo ldconfig

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
