configuration:
  - Debug
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: TRUE

init:
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
install:
  # Update submodules
  - git submodule update --init

  # Build Criterion unit testing framework
  - cd %APPVEYOR_BUILD_FOLDER%\dependencies\criterion
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\dependencies\criterion\build\Release

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config %configuration%
  - ctest
  